---
title: Creating an Executive Dashboard
author: Ben Scheich
date: '2018-08-14'
slug: creating-an-executive-dashboard
categories: []
tags: []
---

I was recently tasked with creating a dashboard for our Board of Directors. Our Board needed an easy way to view the financial and operational health of the organization.  Building a dashboard that could be updated real-time was new to our organization, and I was excited to lead the effort.  

While we have a few Tableau Desktop licenses, building a dashboard with Tableau was not an option. I've found that requiring users to download Tableau Reader to view the dashboard is often difficult for the user, and sharing a package workbook to update the data is cumbersome. Tableau Server would work, but it is prohibitively expensive for our organization.  I needed another option.

Having attended the rstudio::conf in January of 2018, I came back with lots of ideas about how to use R to meet my needs.  Shiny was an option, but deployment of the application was an issue.  I needed something that was free, and the free version of shinyapps.io or the open source version of shiny server were not options.   While talking with our Director of Web Services, we came upon a possible solution: If I could create an .html file that contained all of the dashboard's information, I could ftp the file to a place on the web server and we could share the web link with the Board and Executive team. To automatically update the data, I could create a Windows task that would update the file and push it to the web.  

Luckily, the RStudio team had a solution for creating the html file: flexdashboard.  There are lots of great examples online on how to create a flexdashboard.  The examples made it easy to do, and I was able to build one fairly quickly.  Here is a <p><a href=/files/sample_dashboard.html target="blank"> Sample Dashboard</a></p> based upon the layout that I used.  Of course, the data here aren't real, but I think it conveys the idea.  

Deployment of the file went smoothly, as did the automatic data update.  Our Board of Directors was very impressed with the design and the usability.  They referenced the data in the dashboard numerous times throughout the meetings. And I was excited to add another visual tool to my R aresenal.

Source code for my sample dashboard can be found here.

